language: go
go:
  - 1.6
  - 1.7
  - 1.8
addons:
  apt_packages:
    - pandoc
before_install:
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - export TRAVIS_RUBY_VERSION="$(ruby -e 'puts RUBY_VERSION')-travis"
  - export PATH=~/bin:"$PATH"
  - pip install --user docutils
  - gem install asciidoctor
install:
  - make setup
  - make build
script:
  - make test
