dist: xenial
sudo: required
language: go
cache:
  directories:
    - vendor/bundle
services:
  - docker
go:
  - 1.13.x
before_install:
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - export TRAVIS_RUBY_VERSION="$(ruby -e 'puts RUBY_VERSION')-travis"
  - export PATH=$PATH:~/bin:$PWD/dita-ot-3.4/bin/

  - wget https://github.com/dita-ot/dita-ot/releases/download/3.4/dita-ot-3.4.zip
  - unzip dita-ot-3.4.zip > /dev/null 2>&1

  - sudo apt-get install -y xsltproc
  - pip install --user sphinx
  - gem install asciidoctor
install:
  - make setup
  - # FIXME: make rules
  - make build
script:
  - make test
after_success:
  - # echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - # test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
