dist: xenial
sudo: required
language: python
python: 3.7

before_install:
  - cd docs

install:
  - curl -sL https://install.goreleaser.com/github.com/ValeLint/vale.sh | bash
  - export PATH="./bin:$PATH"
  - vale -v

  - pip install pipenv
  - gem install awesome_bot

script:
  - awesome_bot --allow-dupe --allow-redirect content/*.md

after_success:
  # Build our data sources:
  - pipenv sync
  - markdata --directives='content/directives' content
  # Build our site:
  - mkdocs build --verbose --clean

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/site
  on:
    branch: v2

